def ace():
    print(" --------")
    print("| A      |")
    print("|        |")
    print("|        |")
    print("|      A |")
    print(" --------")
def card2():
    print(" --------")
    print("| 2      |")
    print("|        |")
    print("|        |")
    print("|      2 |")
    print(" --------")
def card3():
    print(" --------")
    print("| 3      |")
    print("|        |")
    print("|        |")
    print("|      3 |")
    print(" --------")
def card4():
    print(" --------")
    print("| 4      |")
    print("|        |")
    print("|        |")
    print("|      4 |")
    print(" --------")
def card5():
    print(" --------")
    print("| 5      |")
    print("|        |")
    print("|        |")
    print("|      5 |")
    print(" --------")
def card6():
    print(" --------")
    print("| 6      |")
    print("|        |")
    print("|        |")
    print("|      6 |")
    print(" --------")
def card7():
    print(" --------")
    print("| 7      |")
    print("|        |")
    print("|        |")
    print("|      7 |")
    print(" --------")
def card8():
    print(" --------")
    print("| 8      |")
    print("|        |")
    print("|        |")
    print("|      8 |")
    print(" --------")
def card9():
    print(" --------")
    print("| 9      |")
    print("|        |")
    print("|        |")
    print("|      9 |")
    print(" --------")
def card10():
    print(" --------")
    print("| 10     |")
    print("|        |")
    print("|        |")
    print("|     10 |")
    print(" --------")

card10()
card9()
card8()
card7()
card6()
card5()
card4()
card3()
card2()
ace()
